### ISSUE TITLE
apagar repo

### ISSUE THREAD

**Issue by drbeco** [OtacilioN/discreta12Disparados#13]
Se juntou com Hugo, apague este. Ok?

**Comment by drbeco** [comment]
Antes de apagar, copie os issues daqui que porventura não estejam de algum modo representados no outro repo.

**Comment by OtacilioN** [comment]
Okay!

**Comment by OtacilioN** [comment]
Done! ( Mentira, not done yet, já que estou comentando aqui, mas em um futuro muito breve repositório está sendo apagado, isso ou já apaguei o repositório e voltei no tempo para deixar esse comentário de done aqui).
